version: '3.8'

networks:
 webapp2-net:
  external: false

services:
 webapp2:
  image: testwebapp2:latest
  container_name: testwebapp2
  hostname: testwebapp2
  depends_on:
   - mongo_image
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - "5000:80"
  environment:
   - mongo__connectionString=mongodb://mongo_image:27018/testing
  networks:
   - webapp2-net
 mongo_image:
  image: mongo:4.2.8
  ports:
   - "27018:27018"
  restart: always
  networks:
   - webapp2-net