version: '3.8'

networks:
 webapp2-net:
  external: false

services:
 webapp2:
  image: testwebapp2:latest
  container_name: testwebapp2
  hostname: testwebapp2
  depends_on:
   - mongo_image
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - "5001:443"
   - "5000:80"
  environment:
   - mongo__connectionString=mongodb://mongo_image:27017/testing
   - Serilog__WriteTo__1__Args__databaseUrl=mongodb://mongo_image:27017/logs
   - ASPNETCORE_URLS=https://+;http://+
   - ASPNETCORE_HTTPS_PORT=443
   - ASPNETCORE_Kestrel__Certificates__Default__Password=crypticpassword
   - ASPNETCORE_Kestrel__Certificates__Default__Path=TestWebApp2.pfx 
  networks:
   - webapp2-net
 mongo_image:
  image: mongo:4.2.8
  ports:
   - "27018:27017"
  restart: always
  networks:
   - webapp2-net